### ISSUE TITLE
flow=none should not satisfy prereqs of already-spawned tasks

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5635]
```
a & b => c   # in flow 1, b fails first try, succeeds second try
```

This will stall with partially satisfied `c` and incomplete failed `a`.

If I re-trigger `b` with `--flow=none` it should not satisfy `c`.

If I re-trigger `b` with `--flow=2` it should, but `c` should carry on with flow number `(1, 2)`

**Comment by oliver-sanders** [comment]
In this example, `1/b` is still in the pool (incomplete outputs), therefore when you trigger it, the flow-nums are extracted from the existing task proxy, not the `--flow` option. I think this is correct / as proposed?

We could also consider failing the `cylc trigger` command if `--flow` is specified AND the task is in the pool.

> If I re-trigger b with --flow=none it should not satisfy c.

This suggests the `--flow` argument **overrides** the flow-numbers of the task proxy in the pool.

> If I re-trigger b with --flow=2 it should, but c should carry on with flow number (1, 2)

This suggests the `--flow` argument **adds** to the flow-numbers of the task proxy in the pool.

**Comment by hjoliver** [comment]
(Note I've just fixed a typo in description ("failed `a`" should have been "failed `b`"; and clarified the `# comment`). 

(I haven't read your comment just above yet)

**Comment by MetRonnie** [comment]
At the moment if I trigger `b` with `--flow none` or `--flow 2` it shows up as flow 1 in the log
```
INFO - [1/b running job:02 flows:1]
```

**Comment by oliver-sanders** [comment]
I think the `--flow` argument does nothing if the task is already in the pool which is kinda correct.

We could consider allowing the `cylc trigger --flow` argument to ADD flow numbers to tasks already in the pool.

Subtracting flow numbers is the domain of `cylc remove`.

So IMO, `cylc trigger --flow=none` for a task in the pool should ideally result in `InputError('Task already exists in flows: {1}')`.

**Comment by TomekTrzeciak** [comment]
> So IMO, `cylc trigger --flow=none` for a task in the pool should ideally result in `InputError('Task already exists in flows: {1}')`.

Why would that need to be an error? I would expect the `--flow=something` option to take effect regardless of the task being in the pool or not.

**Comment by oliver-sanders** [comment]
`cylc trigger` currently means "run this task" (i.e. satisfy queues, xtriggers, prereqs).

If the `cylc trigger --flow` argument is allowed to remove flows, then `cylc trigger --flow=<flow> <task-in-pool>` would be shorthand for:

```
$ cylc remove <task>
$ cylc trigger --flow=<flows> <task>
```

I.E. the compound operation:

1. Prevent the task from spawning downstreams in the flows it is currently in.
2. Re-run the task in the new flows.

If the task is already in the pool then either:

* The task has not run yet (i.e. it has partially satisfied prereqs).
* The task has not completed its required outputs.

I'm not sure why we would want to remove flow numbers from the task AND then re-run it in either case.

**Comment by MetRonnie** [comment]
> Why would that need to be an error? I would expect the `--flow=something` option to take effect regardless of the task being in the pool or not.

At present only tasks that are not currently active can be triggered with a different flow number due to how it's implemented

**Comment by TomekTrzeciak** [comment]
> > Why would that need to be an error? I would expect the `--flow=something` option to take effect regardless of the task being in the pool or not.
> 
> At present only tasks that are not currently active can be triggered with a different flow number due to how it's implemented

Thanks for the clarification @MetRonnie, I didn't realize that was the case. I'm not familiar enough with the latest internals to have a informed opinion, but at the same time I would rather not have to know the internals to understand (at least conceptually) how things work.

> If the `cylc trigger --flow` argument is allowed to remove flows,

And it was not obvious to me at all that this would be implied (sorry for being ignorant).

From [the documentation on reflow](https://cylc.github.io/cylc-doc/latest/html/user-guide/running-workflows/reflow.html):

> `cylc trigger --flow=none ID`
>
> This triggers a task with no flow numbers.
>
> It will not spawn children, and other flows that come by will re-run it.

This doesn't mention anything about active tasks or flow removal, so my naïve interpretation was that it should always work the same, at least conceptually.

As a side note, what I would really love to see one day is something like operational semantics specification for Cylc that would explain the precise behaviour we expect from Cylc and could be used as a basis to decide if the implementation is correct.

**Comment by oliver-sanders** [comment]
Likely resolved by https://github.com/cylc/cylc-flow/pull/6367#issuecomment-2422391861

**Comment by hjoliver** [comment]
#6367 addresses one point covered several times above:
- we can now trigger (e.g.) a final-incomplete `flow=1` task in the active pool with `--flow=2` and it runs and flows on with `flows=(1,2)`

However, it doesn't fix the main topic of this issue:
- if a trigger a final-incomplete `flow=1` task in the active pool with `--flow=none` it runs and flows on with `flow=1`

I think the easiest way to resolve this is to disallow triggering an active-pool task with `--flow=none`. You have to use the default (i.e., the existing flow) or an explicit flow number (to merge with the existing flow).

**Comment by dwsutherland** [comment]
IMHO, with an active task present (waiting or incomplete):
- Not specifying `--flow` should pick up the existing flow by default.
- Specifying a different non-`none` flow should merge from said task onwards (as Hilary has metioned)
- Specifying `--flow=none` (think I'm with Oliver on this one) should spit out and error.. Not sure we should wrap remove and re-"insert" into trigger.. User can choose what to do; remove before, run the one off no-flow, then trigger a flowed/normal if they'd like to continue that branch (or remove `c` otherwise)...

**Comment by hjoliver** [comment]
> Specifying --flow=none (think I'm with Oliver on this one) should spit out and error.. 

That's what I've said too, and done in the PR.

 (In the discussion above I was covering alternative ways of handling it, but decided against).
 
 My final comment just above:
 > The easiest way to resolve this is to simply disallow triggering a flow-assigned active-pool task with --flow=none.
 
 (By disallow I mean "spit out an error")

**Comment by hjoliver** [comment]
Closed by #6433
